name: Java with Maven + Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build without Tests
      run: mvn -B package --file ics/pom.xml -DskipTests
    - name: Build with Tests
      run: mvn -B package --file ics/pom.xml 
    - name: Build the Docker image
      run: docker build --build-arg ICS_DIR=ics . --file ics/Dockerfile --tag my-image-name:$(date +%s)
