# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: 
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Package'  

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Build without Tests
      run: mvn -B package --file ics/pom.xml -DskipTests

    #- name: Build with Maven
    #  run: mvn -B package --file ics/pom.xml 
      
    - name: Run Spring Boot application
      run: mvn spring-boot:run --file ics/pom.xml &

    - name: Wait for application to start
      run: |
          sleep 15 # Adjust this as needed to allow the Spring Boot application to start

    - name: Run Rest-Assured tests
      run: mvn test --file ics/pom.xml
      
    - name: Publish to GitHub Packages
      run:
        mvn -f ics/pom.xml deploy -s $GITHUB_WORKSPACE/settings.xml -Dmaven.test.failure.ignore=true test
        #mvn deploy 
      env:
        GITHUB_TOKEN: ${{ github.token }}
